// lib/app/startup_tones.h
// WAV IDs for self-test tones (generated by tools/gen_alarm_wav.py).
// IDs 13-15 are above WAV_COUNT and are used by both startup.c and test_mode.c.

#ifndef STARTUP_TONES_H
#define STARTUP_TONES_H

#include "hal.h"

#define STARTUP_WAV_LO   13   // 440 Hz
#define STARTUP_WAV_MID  14   // 880 Hz
#define STARTUP_WAV_HI   15   // 1320 Hz

// Set all three MC button LED channels at once.
static inline void rgb(uint16_t r, uint16_t g, uint16_t b) {
    hal_set_led_duty(HAL_LED_RED,   r);
    hal_set_led_duty(HAL_LED_GREEN, g);
    hal_set_led_duty(HAL_LED_BLUE,  b);
}

#endif // STARTUP_TONES_H
